#!/bin/bash

while read userName userLevel password
do
	user=$userName
	while read userName machineName dateStr timeStr message terminal
	do
		if [ $user == $userName ]
		then
			echo "$userName $machineName $dateStr $timeStr"
		fi
	done < ./tables/User_Machine
done < ./tables/User
