#!/bin/bash

while read userName userLevel password
do
	user=$userName
	while read userName machineName dateStr timeStr ttyName
	do
		if [ $user == $userName ]
		then
			echo "$userName $machineName $dateStr $timeStr $ttyName"
		fi
	done < ./tables/User_Machine
done < ./tables/User
